apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/challenge-crf-challenge: "true"
    io.kompose.service: angular-service
  name: angular-service
spec:
  containers:
    - image: bvarandas80/web-angular:v1
      name: angularcontainer
      ports:
        - containerPort: 4200
          hostPort: 4200
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
