apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/challenge-crf-challenge: "true"
    io.kompose.service: challengecrf-api
  name: challengecrf-api
spec:
  containers:
    - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Stage
      image: bvarandas80/challengecrf-api:v1
      name: challengecrf-api
      ports:
        - containerPort: 5200
          hostPort: 5200
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
