apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: challengecrf-queue
  name: challengecrf-queue
spec:
  ports:
    - name: "5303"
      port: 5303
      targetPort: 5303
  selector:
    io.kompose.service: challengecrf-queue
status:
  loadBalancer: {}
