@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/devicons/go.puml

Person(pbc, "Merchant", "A user entry the cash flow information of debit/credit.")

System_Boundary(cfs, "Cash Flow Systen"){
    
    Component(spa, "Single Page Application", "javascript and angular", "Provides all the internet banking functionality to customers via their web browser.")
    Component(hub, "HUB SignalR", "CommandHandler", "Provides Cash Flow Data JSON via SignalR.")
    ComponentDb(db, "Database", "MongoDB", "Stores Cash Flow and DailyConsolidate")
    Component(api, "API", "Controller", "Provides Cash FLow and Daily Consolidated functionality via a JSON/HTTP API.")
    Component(app, "Application/Services", "CommandHandler/QueryHandler", "Lançamentos de fluxo de caixa via JSON/HTTP API.")
    

    ComponentQueue(rmq, "RabbitMq", "Queue", "Publication Cash Flow/Daily Consolitated")

}

Rel(pbc, spa, "Uses", "HTTP")

Rel(spa, api, "Delivers", "JSON")
Rel(api, rmq, "Delivers", "Protobuf")
Rel(rmq, app, "Sends to", "Protobuf")
Rel(app, db, "Writes to", "Entity Framework")
Rel(db, app, "Reads to", "Entity Framework")
Rel(rmq,hub  , "Sends to", "Protobuf")
Rel(hub,spa  , "Sends to", "JSON")

LAYOUT_WITH_LEGEND()

@enduml